#pragma once

#include <Windows.h>

#define DEBUG_OUTPUT 0

#define STEPS_PER_SECOND (1.0f/60.0f)

#define WINDOW_WIDTH 640
#define WINDOW_HEIGHT 640

#define WINDOW_TITLE L"'ROIDS"
#define WINDOW_CLASS L"roids"

#define ASTEROID_SPAWNRATE_SECONDS 12
#define ASTEROID_SPAWNRATE (ASTEROID_SPAWNRATE_SECONDS/STEPS_PER_SECOND)

extern BOOL running;